name: github pages
on: [push, pull_request]
jobs:
  deploy:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - name: Setup Node
        uses: actions/setup-node@v2.1.2
        with:
          node-version: '12.x'
      - run: npm ci
      - run: npm run build

      - name: Move files
        run: |
          mv ./index.html ./dist/

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
          cname: koremp.codesoom.com

          
